const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

function getFiles(dir, fileList = []) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat.isDirectory()) {
            if (file !== 'vendor' && file !== 'scratch' && file !== 'node_modules' && !file.startsWith('.')) {
                getFiles(filePath, fileList);
            }
        } else if (file.endsWith('.js')) {
            fileList.push(filePath);
        }
    }
    return fileList;
}

function parseSymbols(fileContent) {
    const symbols = [];
    const lines = fileContent.split('\n');
    const ignoreKeywords = new Set([
        'if', 'for', 'while', 'switch', 'catch', 'constructor', 'else', 'return', 'try', 'function',
        'const', 'let', 'var', 'class', 'import', 'export', 'default', 'new', 'delete', 'typeof', 'void'
    ]);
    let currentClass = null;
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;
        const classMatch = line.match(/^class\s+([a-zA-Z0-9_$]+)/);
        if (classMatch) {
            currentClass = {
                name: classMatch[1],
                type: 'class',
                methods: [],
                line: i + 1
            };
            symbols.push(currentClass);
            continue;
        }
        const funcDeclMatch = line.match(/(?:async\s+)?function\s+([a-zA-Z0-9_$]+)\s*\(/);
        if (funcDeclMatch) {
            const name = funcDeclMatch[1];
            if (!ignoreKeywords.has(name)) {
                symbols.push({ name, type: 'function', line: i + 1 });
                currentClass = null;
                continue;
            }
        }
        const arrowFuncMatch = line.match(/(?:const|let|var)\s+([a-zA-Z0-9_$]+)\s*=\s*(?:async\s+)?(?:\([^)]*\)|[a-zA-Z0-9_$]+)\s*=>/);
        const exprFuncMatch = line.match(/(?:const|let|var)\s+([a-zA-Z0-9_$]+)\s*=\s*(?:async\s+)?function\s*\(/);
        const assignmentMatch = arrowFuncMatch || exprFuncMatch;
        if (assignmentMatch) {
            const name = assignmentMatch[1];
            if (!ignoreKeywords.has(name)) {
                symbols.push({ name, type: 'function', line: i + 1 });
                currentClass = null;
                continue;
            }
        }
        const methodMatch = line.match(/^(?:async\s+)?([a-zA-Z0-9_$]+)\s*\([^)]*\)\s*\{/);
        if (methodMatch) {
            const name = methodMatch[1];
            if (!ignoreKeywords.has(name)) {
                if (currentClass) {
                    currentClass.methods.push({ name, type: 'method', line: i + 1 });
                } else {
                    symbols.push({ name, type: 'function/method', line: i + 1 });
                }
                continue;
            }
        }
    }
    return symbols;
}
function main() {
    const files = getFiles(rootDir);
    let output = '# Nexus Project Symbols & Functions\n\n';
    output += 'This file is automatically generated. It lists all classes, functions, and methods in the project\'s custom JavaScript source files.\n\n';
    files.sort().forEach(file => {
        const relPath = path.relative(rootDir, file);
        const content = fs.readFileSync(file, 'utf8');
        const symbols = parseSymbols(content);
        if (symbols.length > 0) {
            output += `## [${relPath}](file:///${file})\n\n`;
            symbols.forEach(sym => {
                if (sym.type === 'class') {
                    output += `- **class** \`${sym.name}\` (line ${sym.line})\n`;
                    sym.methods.forEach(m => {
                        output += `  - **method** \`${m.name}\` (line ${m.line})\n`;
                    });
                } else {
                    output += `- **${sym.type}** \`${sym.name}\` (line ${sym.line})\n`;
                }
            });
            output += '\n';
        }
    });
    const outputPath = path.join(rootDir, 'PROJECT_SYMBOLS.md');
    fs.writeFileSync(outputPath, output, 'utf8');
    console.log(`Successfully generated symbols at: ${outputPath}`);
}
main();